import Head from "next/head";
import { AboutMe, Header, LargeCard, Projects } from "@/components/";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <div className="bg-[#FBFEFD] h-screen snap-y md:snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div id="hero" className="md:snap-center">
          <LargeCard />
        </div>
        <div id="projects" className="md:snap-center">
          <Projects />
        </div>
        <div id="about" className="md:snap-center">
          <AboutMe />
        </div>
        <div id="contact" className="md:snap-center">
          <Contact />
        </div>
      </main>
    </div>
  );
}
