import Head from "next/head";
import { AboutMe, Header, LargeCard, Projects } from "@/components/";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jass Bawa | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#FBFEFD] dark:bg-gray-900 h-screen scroll-smooth overflow-scroll z-0">
        <Header />
        <main>
          <div id="hero" className="">
            <LargeCard />
          </div>
          <div id="projects" className="">
            <Projects />
          </div>
          <div id="about" className="">
            <AboutMe />
          </div>
          <div id="contact" className="">
            <Contact />
          </div>
        </main>
      </div>
    </>
  );
}
